#!/usr/bin/env bash
. /opt/zator/webui/cgi-bin/_lib.sh

case "${REQUEST_METHOD:-GET}" in
  GET)
    parse_params
    case "${PARAM_SETTING:-}" in
      wg_blob)
        api_wg_blob_get
        ;;
      wg_state)
        api_wg_state_get
        ;;
      fallback)
        api_fallback_get
        ;;
      udp-games)
        api_udp_games_get
        ;;
      auto_mode)
        api_auto_mode_get
        ;;
      hostlist)
        api_hostlist_get
        ;;
      rst_guard)
        api_rst_guard_get
        ;;
      reasm)
        api_reasm_get
        ;;
      quic443)
        api_quic443_get
        ;;
      dns_desync)
        api_dns_desync_get
        ;;
      ports)
        api_ports_get
        ;;
      provider)
        api_provider_get
        ;;
      *)
        api_tls_blob_get
        ;;
    esac
    ;;
  POST)
    parse_params
    case "${PARAM_SETTING:-}" in
      tls_blob)
        api_tls_blob_set
        ;;
      wg_blob)
        api_wg_blob_set
        ;;
      wg_repeats)
        api_wg_repeats_set
        ;;
      wg_state)
        api_wg_state_set
        ;;
      fallback_state)
        api_fallback_state_set
        ;;
      udp_games_state)
        api_udp_games_set
        ;;
      auto_mode_state)
        api_auto_mode_set
        ;;
      hostlist_state)
        api_hostlist_set
        ;;
      rst_guard_state)
        api_rst_guard_set
        ;;
      reasm_state)
        api_reasm_set
        ;;
      quic443_state)
        api_quic443_set
        ;;
      dns_desync_state)
        api_dns_desync_set
        ;;
      ports_add)
        api_ports_add
        ;;
      ports_remove)
        api_ports_remove
        ;;
      provider_set)
        api_provider_set
        ;;
      provider_redetect)
        api_provider_redetect
        ;;
      *)
        send_error "400 Bad Request" "Неизвестная настройка"
        ;;
    esac
    ;;
  *)
    send_error "405 Method Not Allowed" "Метод не поддерживается"
    ;;
esac
